
export const data = [
    {
        "title": "Son of the forest22w32313",
        "id": 1,
        "platform": "Steam",
        "description": "Juego de supervivencia",
        "genre": "FPS",
        "releaseDate": "2023-08-23",
        "developer": "Activision",
        "publishedby": "Activision",
        "image": "https://i.3djuegos.com/juegos/17036/sons_of_the_forest/fotos/ficha/sons_of_the_forest-5790645.jpg",
        "video": "https://www.youtube.com/embed/8sghWJKPWno?si=QoEhY7gEAyXXg7A5",
        "size": "80GB",
        "price": 70.99
    },
    {
        "title": "Payday 3",
        "id": 2,
        "platform": "Steam",
        "description": "PAYDAY 3 es la esperada secuela de uno de los shooters cooperativos más populares de todos los tiempos. Desde su lanzamiento, los jugadores de PAYDAY han disfrutado de la emoción de un atraco perfectamente planeado y ejecutado. Eso es lo que hace que PAYDAY sea una experiencia de FPS cooperativo de alta octanaje sin igual[^1^][2].",
        "genre": "Disparos en primera persona",
        "releaseDate": "2023-09-21",
        "developer": "Starbreeze Studios",
        "publishedby": "Deep Silver",
        "image": "https://imgs.search.brave.com/XNnrBRw35CF2RGu6ubcPYGyUo_-mG3s14AwWcmM7aRk/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pLmJs/b2dzLmVzL2MwZGJm/MS9zY3JlZW5zaG90/XzM1NjQvMTM2Nl8y/MDAwLndlYnA",
        "video": "https://www.youtube.com/embed/TlkwDNirzF8?si=6P17kcYy4CCqIWKk",
        "size": "65GB",
        "price": 39.99
    },
    {
        "title": "Forza Horizon",
        "id": 3,
        "platform": "Xbox One, Xbox Series X/S, Microsoft Windows",
        "description": "Forza Horizon es un videojuego de carreras que se desarrolla en un mundo abierto basado en varios lugares del mundo real. Los jugadores pueden explorar libremente el mundo del juego mientras participan en carreras y realizan acrobacias para aumentar su nivel de popularidad.",
        "genre": "Videojuego de carreras",
        "releaseDate": "2012-10-23",
        "developer": "Playground Games",
        "publishedby": "Microsoft Studios",
        "image": "https://store-images.s-microsoft.com/image/apps.49800.13718773309227929.bebdcc0e-1ed5-4778-8732-f4ef65a2f445.9ac09d39-064d-466c-81ca-2f1b6f0b95c5",
        "video": "https://www.youtube.com/embed/Rv7xLt5yNsM?si=dhLvaQnsmfsvEqnh",
        "size": "103GB",
        "price": 59.99
    },
    {
        "title": "FIFA 24",
        "id": 4,
        "platform": "PS5, Switch, PC, PS4, Xbox Series X/S y Xbox One",
        "description": "FIFA 24 es un videojuego de fútbol para Nintendo Switch, PlayStation 4, PlayStation 5, Xbox One, Xbox Series y PC que forma parte de la saga de simuladores deportivos de Electronic Arts, siendo el sucesor de FIFA 23. Con modos en solitario y con énfasis en el online, así como con un FIFA Ultimate Team renovado, ofrece de nuevo todas las licencias de las principales ligas europeas y americanas, el retorno de modos clásicos y una ración de mejoras técnicas gráficas y jugables[^1^][1].",
        "genre": "Deportes / Fútbol",
        "releaseDate": "2023-09-21",
        "developer": "EA Sports",
        "publishedby": "EA Swiss Sarl",
        "image": "https://imgs.search.brave.com/HiIivhEoEub5mwhLjG0mEh9qj2QGeC8pUPhGrqFfOZg/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pLmJs/b2dzLmVzLzFiZjEx/My9lYXNwb3J0cy1w/b3J0YWRhLzQ1MF8x/MDAwLmpwZWc",
        "video": "https://www.youtube.com/embed/L30zvMbVJlM?si=BhKHJ7PcK5PJMkpw",
        "size": "24GB",
        "price": 24.99
    },
    {
        "title": "Call of Duty: Modern Warfare 3",
        "id": 5,
        "platform": "Windows, OS X, Nintendo DS, GameCube, Nokia N-Gage, PlayStation 2, PlayStation 3, PlayStation 4, PlayStation 5, PlayStation Portable, PlayStation Vita, Wii, Wii U, Xbox, Xbox 360, Xbox One, Xbox Series X/S, iOS, Android, BlackBerry, J2ME",
        "description": "Call of Duty: Modern Warfare 3 es un videojuego de disparos en primera persona desarrollado por Sledgehammer Games y Activision. La historia continúa justo donde lo dejó Call of Duty: Modern Warfare 2 (2022), ofreciendo algunos de los mapas más amplios de toda la saga, y además de la campaña para un jugador también incluye el tradicional multijugador competitivo y un nuevo modo zombis en mundo abierto[^1^][2].",
        "genre": "Disparos en primera persona",
        "releaseDate": "2023-11-10",
        "developer": "Sledgehammer Games",
        "publishedby": "Activision",
        "image": "https://imgs.search.brave.com/GcEfTg8zOacxOCgqti7QjBevv272GSBvK-THuBQ5fjg/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZS5hcGkucGxheXN0/YXRpb24uY29tL3Z1/bGNhbi9hcC9ybmQv/MjAyMzA4LzE0MTUv/YTQzZjdhOWUyOGIw/ZmY4MWQ4MmY5YTgz/YmM4NWQ1ZDVmZTU5/YjZmN2JkZDY4Mjhm/LmpwZw",
        "video": "https://www.youtube.com/embed/CEeVm-dGVKQ?si=cJMPSfqydbQjFK4s",
        "size": "64GB",
        "price": 12.99
    },
    {
        "title": "Far Cry 6",
        "id": 6,
        "platform": "Xbox Series X|S, Xbox One, PS5, PS4, Stadia, Epic Games y Ubisoft Connect",
        "description": "Far Cry 6 es un videojuego de disparos en primera persona desarrollado por Ubisoft Toronto y publicado por Ubisoft. Es la sexta entrega principal de la serie Far Cry y sucesora de Far Cry 5 de 2018. El juego está ambientado en la isla caribeña ficticia de Yara, gobernada como una dictadura por 'El Presidente' Antón Castillo (interpretado por Giancarlo Esposito) que está criando a su hijo Diego (Anthony Gonzalez) para seguir en su gobierno. Los jugadores asumen el papel de Dani Rojas (con la voz de Nisa Gunduz o Sean Rey), un luchador guerrillero que intenta derrocar a Castillo y su régimen[^1^][2].",
        "genre": "Disparos en primera persona",
        "releaseDate": "2021-10-07",
        "developer": "Ubisoft Toronto",
        "publishedby": "Ubisoft",
        "image": "https://imgs.search.brave.com/2cs7wF5HAsstpXNO1gS0q2sI6dMKs6Tj9WJSHLtTnbc/rs:fit:860:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXIuZG9nL2xh/cmdlLzIwNDU4NjA1/LmpwZw",
        "video": "https://www.youtube.com/embed/IYoya-4DCbs?si=gKyCoAueiwCOEge4",
        "size": "30GB",
        "price": 25.99
    },
    {
        "title": "Grand Theft Auto V",
        "id": 7,
        "platform": "Steam",
        "description": "Grand Theft Auto V es un videojuego de acción-aventura de mundo abierto desarrollado por la compañía británica Rockstar North y distribuido por Rockstar Games.",
        "genre": "Acción, Aventura",
        "releaseDate": "2013-09-17",
        "developer": "Rockstar North",
        "publishedby": "Rockstar Games",
        "image": "https://imgs.search.brave.com/MYlp5k5JdRKlqtGduBNfaC_cSjlxjtVLL7iIVtT-Wdg/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZS5hcGkucGxheXN0/YXRpb24uY29tL2Nk/bi9VUDEwMDQvQ1VT/QTAwNDE5XzAwL2JU/TlNlN29rOGVGVkdl/UUJ5QTVxU3pCUW9L/QUFZMzJSLnBuZw",
        "video": "https://www.youtube.com/embed/hvoD7ehZPcM?si=CipCrwZ-mtiGo3mV",
        "size": "72GB",
        "price": 30.99
    },
    {
        "title": "Assetto Corsa",
        "id": 8,
        "platform": "Steam",
        "description": "Assetto Corsa es un videojuego de simulación de carreras desarrollado por el desarrollador de videojuegos italiano Kunos Simulazioni. Está diseñado con un énfasis en una experiencia de carreras realista con soporte para una amplia personalización y modificabilidad[^1^][2].",
        "genre": "Simulación de carreras",
        "releaseDate": "2014-12-19",
        "developer": "Kunos Simulazioni",
        "publishedby": "Kunos Simulazioni",
        "image": "https://imgs.search.brave.com/WkKDiplktVAa_N-ndiJE7SlunsZpFF6YBunTbDEQiMs/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9nYW1p/bmctY2RuLmNvbS9p/bWFnZXMvcHJvZHVj/dHMvMTI2My8zODB4/MjE4L2Fzc2V0dG8t/Y29yc2EtcGMtanVl/Z28tc3RlYW0tY292/ZXIuanBnP3Y9MTY5/MzUxMTA2MA",
        "video": "https://www.youtube.com/embed/2naR61zAD-Q?si=F5ggnP_w8CLaHVZQ",
        "size": "54GB",
        "price": 19.99
    },
    {
        "title": "Age of Empires IV: The Sultans Ascend",
        "id": 9,
        "platform": "Steam",
        "description": "Age of Empires IV: The Sultans Ascend es la primera expansión esperada de Age of Empires IV. Esta nueva campaña para un jugador tiene lugar en Oriente Medio durante las Cruzadas europeas. Juega como la resistencia musulmana a la invasión y sigue la historia de líderes musulmanes conocidos, sus luchas con los cruzados y las batallas que libraron[^1^][1]. La expansión incluye dos civilizaciones completamente nuevas, los japoneses y los bizantinos, y cuatro civilizaciones variantes jugables que revisitan y reimaginan algunas de las primeras civilizaciones del lanzamiento principal de Age of Empires IV[^1^][1].",
        "genre": "Estrategia en tiempo real",
        "releaseDate": "2023-12-14",
        "developer": "Relic Entertainment",
        "publishedby": "Xbox Game Studios",
        "image": "https://imgs.search.brave.com/Z6r4usNxLzsF1gXHZ8iyVTvNBVr9oji7566p9I8a0Sk/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMueGJveHNlcnZp/Y2VzLmNvbS9hc3Nl/dHMvZjYvYzEvZjZj/MWI2MjUtZTQ2Zi00/MjliLTk3MjctOWEy/NGMzMTExNzM3Lmpw/Zz9uPTcyMTE1NjZf/R0xQLVBhZ2UtSGVy/by0wXzEwODN4NjA5/LmpwZw",
        "video": "https://www.youtube.com/embed/_j-uv3lN3B4?si=hj_2uUBSfjadxMu4",
        "size": "N/A",
        "price": 19.99
    },
    {
        "title": "God of War: Ragnarok",
        "id": 10,
        "platform": "PlayStation 5, PlayStation 4",
        "description": "God of War: Ragnarok es la nueva aventura de acción y rol para PlayStation 5 y PlayStation 4, continuación de God of War de 2018, uno de los títulos más exitosos de la plataforma de sobremesa de Sony. Desarrollado por el prestigioso estudio Sony Santa Monica, nos presenta una nueva historia en la que Kratos deberá enfrentarse a diversos enemigos de inspiración nórdica, explorando los mitos del Ragnarok, el apocalipsis que todo lo devorará según esta tradición del norte[^1^][2].",
        "genre": "Aventura de acción",
        "releaseDate": "2022-11-09",
        "developer": "Sony Santa Monica",
        "publishedby": "Sony Interactive Entertainment",
        "image": "https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png",
        "video": "https://www.youtube.com/embed/F3jePdO9_jc?si=SYpbJTjedAfpwNK-",
        "size": "N/A",
        "price": 55.99
    }

]

