
export const data = [
    {
        "title": "Son of the forest",
        "id": 1,
        "platform": "Steam",
        "description": "  Survival FPS by Activision. Uncover the secrets of a mysterious forest in this intense survival game. Encounter hostile creatures, craft tools, and strive to survive against the backdrop of stunning visuals and gripping gameplay. ",
        "genre": "Survival",
        "releaseDate": "2023-08-23",
        "developer": "Activision",
        "publishedby": "Activision",
        "video": "https://www.youtube.com/embed/8sghWJKPWno?si=QoEhY7gEAyXXg7A5",
        "image": "https://github.com/zuoki/imagenesPF/blob/main/Son%20of%20the%20forest/caratula.png?raw=true",
        "wallpeaper": "https://github.com/zuoki/imagenesPF/blob/main/Son%20of%20the%20forest/wallpeaper.png?raw=true",
        "capture": "https://github.com/zuoki/imagenesPF/blob/main/Son%20of%20the%20forest/captura.png?raw=true",
        "size": "80GB",
        "price": 70.99
    },
    {
        "title": "Call of Duty: Modern Warfare 3",
        "id": 2,
        "description": "Epic FPS Campaign and Multiplayer. Join the intense FPS action with Modern Warfare 3. Experience a gripping single-player campaign, engage in competitive multiplayer battles, and explore a new open-world zombie mode. Sledgehammer Games delivers an adrenaline-pumping sequel.",
        "genre": "FPS",
        "releaseDate": "2023-11-10",
        "developer": "Sledgehammer Games",
        "publishedby": "Activision",
        "image": "https://github.com/zuoki/imagenesPF/blob/main/Call%20of%20Duty%20Modern%20Warfare%203/caratula.png?raw=true",
        "wallpeaper":"https://github.com/zuoki/imagenesPF/blob/main/Call%20of%20Duty%20Modern%20Warfare%203/wallpeaper.png?raw=true",
        "capture":"https://github.com/zuoki/imagenesPF/blob/main/Call%20of%20Duty%20Modern%20Warfare%203/captura.png?raw=true",       
        "video": "https://www.youtube.com/embed/CEeVm-dGVKQ?si=cJMPSfqydbQjFK4s",
        "size": "64GB",
        "price": 12.99,
    },
    {
        "title": "Forza Horizon",
        "id": 3,
        "platform": "Xbox",
        "description": "Open-world Racing Adventure. Immerse yourself in the exhilarating world of open-world racing. Explore diverse locations, participate in races, and showcase your skills in stunts. Forza Horizon delivers a thrilling racing experience with stunning visuals and dynamic gameplay.",
        "genre": "Sports",
        "releaseDate": "2012-10-23",
        "developer": "Playground Games",
        "publishedby": "Microsoft Studios",
        "image": "https://github.com/zuoki/imagenesPF/blob/main/Forza%20Horizon/caratula.png?raw=true",
        "wallpeaper":"https://github.com/zuoki/imagenesPF/blob/main/Forza%20Horizon/wallpeaper.png?raw=true",
        "capture":"https://github.com/zuoki/imagenesPF/blob/main/Forza%20Horizon/captura.png?raw=true",
        "video": "https://www.youtube.com/embed/Rv7xLt5yNsM?si=dhLvaQnsmfsvEqnh",
        "size": "103GB",
        "price": 59.99
    },
    {
        "title": "FIFA 24",
        "id": 4,
        "platform": "Origin",
        "description": "Football Simulator for All Platforms. FIFA 24, the latest installment, offers a comprehensive football experience. Engage in solo or online modes, enjoy an enhanced FIFA Ultimate Team, and savor improved graphics and gameplay across various platforms.",
        "genre": "Sports",
        "releaseDate": "2023-09-21",
        "developer": "EA Sports",
        "publishedby": "EA Swiss Sarl",
        "image": "https://github.com/zuoki/imagenesPF/blob/main/FIFA%2024/caratula.png?raw=true",
        "wallpeaper":"https://github.com/zuoki/imagenesPF/blob/main/FIFA%2024/wallpeaper.png?raw=true",
        "capture":"https://github.com/zuoki/imagenesPF/blob/main/FIFA%2024/captura.png?raw=true",       
        "video": "https://www.youtube.com/embed/L30zvMbVJlM?si=BhKHJ7PcK5PJMkpw",
        "size": "24GB",
        "price": 24.99
    },
    {
        "title": "Payday 3",
        "id": 5,
        "platform": "Steam",
        "description": "Cooperative Heist FPS. Dive into the high-stakes world of cooperative heists. Plan and execute perfect robberies with friends, experiencing the adrenaline of intense first-person shooter action in PAYDAY 3's thrilling sequel.",
        "genre": "FPS",
        "releaseDate": "2023-09-21",
        "developer": "Starbreeze Studios",
        "publishedby": "Deep Silver",
        "image": "https://github.com/zuoki/imagenesPF/blob/main/Payday%203/caratula.png?raw=true",
        "wallpeaper": "https://github.com/zuoki/imagenesPF/blob/main/Payday%203/wallpeaper.png?raw=true",
        "capture": "https://github.com/zuoki/imagenesPF/blob/main/Payday%203/captura.png?raw=true",
        "video": "https://www.youtube.com/embed/TlkwDNirzF8?si=6P17kcYy4CCqIWKk",
        "size": "65GB",
        "price": 39.99,
    },
    {
        "title": "Far Cry 6",
        "id": 6,
        "platform": "Epic G",
        "description": "First-person Shooter in Yara. Fight against the oppressive regime of Antón Castillo in Far Cry 6. Play as guerrilla fighter Dani Rojas and lead a revolution on the fictional Caribbean island of Yara. Explore a captivating narrative with intense FPS gameplay..",
        "genre": "FPS",
        "releaseDate": "2021-10-07",
        "developer": "Ubisoft Toronto",
        "publishedby": "Ubisoft",
        "image": "https://github.com/zuoki/imagenesPF/blob/main/Far%20Cry%206/caratula.png?raw=true",
        "wallpeaper":"https://github.com/zuoki/imagenesPF/blob/main/Far%20Cry%206/wallpeaper.png?raw=true",
        "capture":"https://github.com/zuoki/imagenesPF/blob/main/Far%20Cry%206/captura.png?raw=true",       
        "video": "https://www.youtube.com/embed/IYoya-4DCbs?si=gKyCoAueiwCOEge4",
        "size": "30GB",
        "price": 25.99
    },
    {
        "title": "Grand Theft Auto V",
        "id": 7,
        "platform": "Steam",
        "description": "Open-world Action Adventure. GTA V immerses players in a sprawling open world of crime and chaos. Follow the interconnected lives of three protagonists as they navigate the criminal underworld, offering a gripping narrative alongside the freedom of sandbox exploration.",
        "genre": "Acction",
        "releaseDate": "2013-09-17",
        "developer": "Rockstar North",
        "publishedby": "Rockstar Games",
        "image": "https://github.com/zuoki/imagenesPF/blob/main/Grand%20Theft%20Auto%20V/caratula.png?raw=true",
        "wallpeaper":"https://github.com/zuoki/imagenesPF/blob/main/Grand%20Theft%20Auto%20V/wallpeaper.png?raw=true",
        "capture":"https://github.com/zuoki/imagenesPF/blob/main/Grand%20Theft%20Auto%20V/captura.png?raw=true",
        "video": "https://www.youtube.com/embed/QkkoHAzjnUs?si=cdObb5_g1U9-6SHy",
        "size": "72GB",
        "price": 30.99
    },
    {
        "title": "Assetto Corsa",
        "id": 8,
        "platform": "Steam",
        "description": "Realistic Racing Simulation. Assetto Corsa provides an authentic racing experience with extensive customization. Immerse yourself in realistic physics, precise controls, and a variety of tracks and cars. Kunos Simulazioni delivers a simulator tailored for racing enthusiasts.",
        "genre": "Simulator",
        "releaseDate": "2014-12-19",
        "developer": "Kunos Simulazioni",
        "publishedby": "Kunos Simulazioni",
        "image": "https://github.com/zuoki/imagenesPF/blob/main/Assetto%20Corsa/caratula.png?raw=true",
        "wallpeaper":"https://github.com/zuoki/imagenesPF/blob/main/Assetto%20Corsa/wallpeaper.png?raw=true",
        "capture":"https://github.com/zuoki/imagenesPF/blob/main/Assetto%20Corsa/captura.png?raw=true",       
         "video": "https://www.youtube.com/embed/2naR61zAD-Q?si=F5ggnP_w8CLaHVZQ",
        "size": "54GB",
        "price": 19.99
    },
    {
        "title": "Age of Empires IV: The Sultans Ascend",
        "id": 9,
        "platform": "Steam",
        "description": "Real-time Strategy Expansion. The Sultans Ascend expansion for Age of Empires IV unfolds a compelling single-player campaign set in the Middle East during the Crusades. Lead the Muslim resistance, explore historical battles, and enjoy new civilizations, adding depth to the acclaimed strategy game.",
        "genre": "Estrategy",
        "releaseDate": "2023-12-14",
        "developer": "Relic Entertainment",
        "publishedby": "Xbox Game Studios",
        "image": "https://github.com/zuoki/imagenesPF/blob/main/Age%20of%20Empires%20IV%20The%20Sultans%20Ascend/caratula.png?raw=true",
        "wallpeaper":"https://github.com/zuoki/imagenesPF/blob/main/Age%20of%20Empires%20IV%20The%20Sultans%20Ascend/wallpeaper.png?raw=true",
        "capture":"https://github.com/zuoki/imagenesPF/blob/main/Age%20of%20Empires%20IV%20The%20Sultans%20Ascend/captura.png?raw=true",      
        "video": "https://www.youtube.com/embed/_j-uv3lN3B4?si=hj_2uUBSfjadxMu4",
        "size": "N/A",
        "price": 19.99
    },
    {
        "title": "God of War: Ragnarok",
        "id": 10,
        "platform": "Steam",
        "description": "Norse-inspired Action Adventure. God of War: Ragnarok continues Kratos' saga with Norse mythology. Face formidable foes, explore the mysteries of Ragnarok, and delve into a rich narrative. Sony Santa Monica delivers a visually stunning and emotionally charged action-adventure for PlayStation 5 and PlayStation 4.",
        "genre": "Adventure",
        "releaseDate": "2022-11-09",
        "developer": "Sony Santa Monica",
        "publishedby": "Sony Interactive Entertainment",
        "image": "https://github.com/zuoki/imagenesPF/blob/main/God%20of%20War%20Ragnarok/caratula.png?raw=true",
        "wallpeaper":"https://github.com/zuoki/imagenesPF/blob/main/God%20of%20War%20Ragnarok/wallpeaper.png?raw=true",
        "capture":"https://github.com/zuoki/imagenesPF/blob/main/God%20of%20War%20Ragnarok/captura.png?raw=true",      
        "video": "https://www.youtube.com/embed/F3jePdO9_jc?si=SYpbJTjedAfpwNK-",
        "size": "76GB",
        "price": 55.99
    }

]

