
export const data = [
    {
        "title": "Son of the forest",
        "id": 1,
        "platform": "Steam",
        "description": "  Survival FPS by Activision. Uncover the secrets of a mysterious forest in this intense survival game. Encounter hostile creatures, craft tools, and strive to survive against the backdrop of stunning visuals and gripping gameplay. ",
        "genre": "FPS",
        "releaseDate": "2023-08-23",
        "developer": "Activision",
        "publishedby": "Activision",
        "video": "https://www.youtube.com/embed/8sghWJKPWno?si=QoEhY7gEAyXXg7A5",
        "image": "https://github.com/zuoki/imagenesPF/blob/main/Son%20of%20the%20forest/caratula.png?raw=true",
        "wallpeaper":"https://github.com/zuoki/imagenesPF/blob/main/Son%20of%20the%20forest/wallpeaper.png?raw=true",
        "capture":"https://github.com/zuoki/imagenesPF/blob/main/Son%20of%20the%20forest/captura.png?raw=true",
        "size": "80GB",
        "price": 70.99
    },
    {
        "title": "Payday 3",
        "id": 2,
        "platform": "Steam",
        "description": "Cooperative Heist FPS. Dive into the high-stakes world of cooperative heists. Plan and execute perfect robberies with friends, experiencing the adrenaline of intense first-person shooter action in PAYDAY 3's thrilling sequel.",
        "genre": "FPS",
        "releaseDate": "2023-09-21",
        "developer": "Starbreeze Studios",
        "publishedby": "Deep Silver",
        "image": "https://github.com/zuoki/imagenesPF/blob/main/Payday%203/caratula.png?raw=true",
        "wallpeaper":"https://github.com/zuoki/imagenesPF/blob/main/Payday%203/wallpeaper.png?raw=true",
        "capture":"https://github.com/zuoki/imagenesPF/blob/main/Payday%203/captura.png?raw=true",
        "video": "https://www.youtube.com/embed/TlkwDNirzF8?si=6P17kcYy4CCqIWKk",
        "size": "65GB",
        "price": 39.99
    },
    {
        "title": "Forza Horizon",
        "id": 3,
        "platform": "Xbox One, Xbox Series X/S, Microsoft Windows",
        "description": "Open-world Racing Adventure. Immerse yourself in the exhilarating world of open-world racing. Explore diverse locations, participate in races, and showcase your skills in stunts. Forza Horizon delivers a thrilling racing experience with stunning visuals and dynamic gameplay.",
        "genre": "Sports",
        "releaseDate": "2012-10-23",
        "developer": "Playground Games",
        "publishedby": "Microsoft Studios",
        "image": "https://store-images.s-microsoft.com/image/apps.49800.13718773309227929.bebdcc0e-1ed5-4778-8732-f4ef65a2f445.9ac09d39-064d-466c-81ca-2f1b6f0b95c5",
        "video": "https://www.youtube.com/embed/Rv7xLt5yNsM?si=dhLvaQnsmfsvEqnh",
        "size": "103GB",
        "price": 59.99
    },
    {
        "title": "FIFA 24",
        "id": 4,
        "platform": "PS5, Switch, PC, PS4, Xbox Series X/S y Xbox One",
        "description": "Football Simulator for All Platforms. FIFA 24, the latest installment, offers a comprehensive football experience. Engage in solo or online modes, enjoy an enhanced FIFA Ultimate Team, and savor improved graphics and gameplay across various platforms.",
        "genre": "Sports",
        "releaseDate": "2023-09-21",
        "developer": "EA Sports",
        "publishedby": "EA Swiss Sarl",
        "image": "https://imgs.search.brave.com/HiIivhEoEub5mwhLjG0mEh9qj2QGeC8pUPhGrqFfOZg/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pLmJs/b2dzLmVzLzFiZjEx/My9lYXNwb3J0cy1w/b3J0YWRhLzQ1MF8x/MDAwLmpwZWc",
        "video": "https://www.youtube.com/embed/L30zvMbVJlM?si=BhKHJ7PcK5PJMkpw",
        "size": "24GB",
        "price": 24.99
    },
    {
        "title": "Call of Duty: Modern Warfare 3",
        "id": 5,
        "platform": "Windows, OS X, Nintendo DS, GameCube, Nokia N-Gage, PlayStation 2, PlayStation 3, PlayStation 4, PlayStation 5, PlayStation Portable, PlayStation Vita, Wii, Wii U, Xbox, Xbox 360, Xbox One, Xbox Series X/S, iOS, Android, BlackBerry, J2ME",
        "description": "Epic FPS Campaign and Multiplayer. Join the intense FPS action with Modern Warfare 3. Experience a gripping single-player campaign, engage in competitive multiplayer battles, and explore a new open-world zombie mode. Sledgehammer Games delivers an adrenaline-pumping sequel.",
        "genre": "FPS",
        "releaseDate": "2023-11-10",
        "developer": "Sledgehammer Games",
        "publishedby": "Activision",
        "image": "https://imgs.search.brave.com/GcEfTg8zOacxOCgqti7QjBevv272GSBvK-THuBQ5fjg/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZS5hcGkucGxheXN0/YXRpb24uY29tL3Z1/bGNhbi9hcC9ybmQv/MjAyMzA4LzE0MTUv/YTQzZjdhOWUyOGIw/ZmY4MWQ4MmY5YTgz/YmM4NWQ1ZDVmZTU5/YjZmN2JkZDY4Mjhm/LmpwZw",
        "video": "https://www.youtube.com/embed/CEeVm-dGVKQ?si=cJMPSfqydbQjFK4s",
        "size": "64GB",
        "price": 12.99
    },
    {
        "title": "Far Cry 6",
        "id": 6,
        "platform": "Xbox Series X|S, Xbox One, PS5, PS4, Stadia, Epic Games y Ubisoft Connect",
        "description": "First-person Shooter in Yara. Fight against the oppressive regime of Antón Castillo in Far Cry 6. Play as guerrilla fighter Dani Rojas and lead a revolution on the fictional Caribbean island of Yara. Explore a captivating narrative with intense FPS gameplay..",
        "genre": "FPS",
        "releaseDate": "2021-10-07",
        "developer": "Ubisoft Toronto",
        "publishedby": "Ubisoft",
        "image": "https://imgs.search.brave.com/2cs7wF5HAsstpXNO1gS0q2sI6dMKs6Tj9WJSHLtTnbc/rs:fit:860:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXIuZG9nL2xh/cmdlLzIwNDU4NjA1/LmpwZw",
        "video": "https://www.youtube.com/embed/IYoya-4DCbs?si=gKyCoAueiwCOEge4",
        "size": "30GB",
        "price": 25.99
    },
    {
        "title": "Grand Theft Auto V",
        "id": 7,
        "platform": "Steam",
        "description": "Open-world Action Adventure. GTA V immerses players in a sprawling open world of crime and chaos. Follow the interconnected lives of three protagonists as they navigate the criminal underworld, offering a gripping narrative alongside the freedom of sandbox exploration.",
        "genre": "Acction",
        "releaseDate": "2013-09-17",
        "developer": "Rockstar North",
        "publishedby": "Rockstar Games",
        "image": "https://imgs.search.brave.com/MYlp5k5JdRKlqtGduBNfaC_cSjlxjtVLL7iIVtT-Wdg/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZS5hcGkucGxheXN0/YXRpb24uY29tL2Nk/bi9VUDEwMDQvQ1VT/QTAwNDE5XzAwL2JU/TlNlN29rOGVGVkdl/UUJ5QTVxU3pCUW9L/QUFZMzJSLnBuZw",
        "video": "https://www.youtube.com/embed/hvoD7ehZPcM?si=CipCrwZ-mtiGo3mV",
        "size": "72GB",
        "price": 30.99
    },
    {
        "title": "Assetto Corsa",
        "id": 8,
        "platform": "Steam",
        "description": "Realistic Racing Simulation. Assetto Corsa provides an authentic racing experience with extensive customization. Immerse yourself in realistic physics, precise controls, and a variety of tracks and cars. Kunos Simulazioni delivers a simulator tailored for racing enthusiasts.",
        "genre": "Simulator",
        "releaseDate": "2014-12-19",
        "developer": "Kunos Simulazioni",
        "publishedby": "Kunos Simulazioni",
        "image": "https://imgs.search.brave.com/WkKDiplktVAa_N-ndiJE7SlunsZpFF6YBunTbDEQiMs/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9nYW1p/bmctY2RuLmNvbS9p/bWFnZXMvcHJvZHVj/dHMvMTI2My8zODB4/MjE4L2Fzc2V0dG8t/Y29yc2EtcGMtanVl/Z28tc3RlYW0tY292/ZXIuanBnP3Y9MTY5/MzUxMTA2MA",
        "video": "https://www.youtube.com/embed/2naR61zAD-Q?si=F5ggnP_w8CLaHVZQ",
        "size": "54GB",
        "price": 19.99
    },
    {
        "title": "Age of Empires IV: The Sultans Ascend",
        "id": 9,
        "platform": "Steam",
        "description": "Real-time Strategy Expansion. The Sultans Ascend expansion for Age of Empires IV unfolds a compelling single-player campaign set in the Middle East during the Crusades. Lead the Muslim resistance, explore historical battles, and enjoy new civilizations, adding depth to the acclaimed strategy game.",
        "genre": "Estrategy",
        "releaseDate": "2023-12-14",
        "developer": "Relic Entertainment",
        "publishedby": "Xbox Game Studios",
        "image": "https://imgs.search.brave.com/Z6r4usNxLzsF1gXHZ8iyVTvNBVr9oji7566p9I8a0Sk/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMueGJveHNlcnZp/Y2VzLmNvbS9hc3Nl/dHMvZjYvYzEvZjZj/MWI2MjUtZTQ2Zi00/MjliLTk3MjctOWEy/NGMzMTExNzM3Lmpw/Zz9uPTcyMTE1NjZf/R0xQLVBhZ2UtSGVy/by0wXzEwODN4NjA5/LmpwZw",
        "video": "https://www.youtube.com/embed/_j-uv3lN3B4?si=hj_2uUBSfjadxMu4",
        "size": "N/A",
        "price": 19.99
    },
    {
        "title": "God of War: Ragnarok",
        "id": 10,
        "platform": "PlayStation 5, PlayStation 4",
        "description": "Norse-inspired Action Adventure. God of War: Ragnarok continues Kratos' saga with Norse mythology. Face formidable foes, explore the mysteries of Ragnarok, and delve into a rich narrative. Sony Santa Monica delivers a visually stunning and emotionally charged action-adventure for PlayStation 5 and PlayStation 4.",
        "genre": "Adventure",
        "releaseDate": "2022-11-09",
        "developer": "Sony Santa Monica",
        "publishedby": "Sony Interactive Entertainment",
        "image": "https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png",
        "video": "https://www.youtube.com/embed/F3jePdO9_jc?si=SYpbJTjedAfpwNK-",
        "size": "N/A",
        "price": 55.99
    }

]

