export const games = [ 
    {
        "id": 1,
        "titulo": "The Witcher 3: Wild Hunt",
        "plataformas": ["Steam", "Epic Games", "Blizzard"],
        "genero": ["RPG", "Acción"],
        "fecha": "19/05/2015",
        "desarrollador": "CD Projekt",
        "editor": ["CD Projekt", "Bandai Namco Entertainment"],
        "stock": 80,
        "caratula": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/caratula.png?raw=true",
        "captura": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/captura.png?raw=true",
        "wallpeaper": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/wallpeaper.png?raw=true",
        "precio": 39.99
    },
    {
        "id": 2,
        "titulo": "Cyberpunk 2077",
        "plataformas": ["Steam", "Epic Games", "Blizzard"],
        "genero": ["RPG", "Acción", "CienciaFicción"],
        "fecha": "10/12/2020",
        "desarrollador": "CD Projekt",
        "editor": ["CD Projekt", "Bandai Namco Entertainment"],
        "stock": 60,
        "caratula": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/caratula.png?raw=true",
        "captura": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/captura.png?raw=true",
        "wallpeaper": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/wallpeaper.png?raw=true",
        "precio": 49.99,
        "offert": [true, 15]
    },
    {
        "id": 3,
        "titulo": "Assassin's Creed Valhalla",
        "plataformas": ["Steam", "Epic Games", "Blizzard"],
        "genero": ["Aventura", "Acción", "Histórico"],
        "fecha": "10/11/2020",
        "desarrollador": "Ubisoft Montreal",
        "editor": ["Ubisoft"],
        "stock": 75,
        "caratula": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/caratula.png?raw=true",
        "captura": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/captura.png?raw=true",
        "wallpeaper": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/wallpeaper.png?raw=true",
        "precio": 54.99
    },
    {
        "id": 4,
        "titulo": "Red Dead Redemption 2",
        "plataformas": ["Steam", "Epic Games", "Blizzard"],
        "genero": ["Acción", "Aventura", "Western"],
        "fecha": "26/10/2018",
        "desarrollador": "Rockstar Studios",
        "editor": ["Rockstar Games"],
        "stock": 90,
        "caratula": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/caratula.png?raw=true",
        "captura": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/captura.png?raw=true",
        "wallpeaper": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/wallpeaper.png?raw=true",
        "precio": 59.99,
        "offert": [true, 45]
    },
    {
        "id": 5,
        "titulo": "FIFA 22",
        "plataformas": ["Steam", "Epic Games", "Blizzard"],
        "genero": ["Deportes", "Simulación"],
        "fecha": "01/10/2021",
        "desarrollador": "EA Vancouver",
        "editor": ["EA Sports"],
        "stock": 80,
        "caratula": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/caratula.png?raw=true",
        "captura": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/captura.png?raw=true",
        "wallpeaper": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/wallpeaper.png?raw=true",
        "precio": 44.99
    },
    {
        "id": 6,
        "titulo": "Minecraft",
        "plataformas": ["Steam", "Epic Games", "Blizzard"],
        "genero": ["Sandbox", "Aventura"],
        "fecha": "17/05/2009",
        "desarrollador": "Mojang Studios",
        "editor": ["Mojang"],
        "stock": 70,
        "caratula": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/caratula.png?raw=true",
        "captura": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/captura.png?raw=true",
        "wallpeaper": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/wallpeaper.png?raw=true",
        "precio": 29.99,
        "offert": [true, 30]
    },
    {
        "id": 7,
        "titulo": "Call of Duty: Warzone",
        "plataformas": ["Steam", "Epic Games", "Blizzard"],
        "genero": ["Shooter", "BattleRoyale", "Simulación"],
        "fecha": "10/03/2020",
        "desarrollador": "Infinity Ward",
        "editor": ["Activision"],
        "stock": 85,
        "caratula": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/caratula.png?raw=true",
        "captura": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/captura.png?raw=true",
        "wallpeaper": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/wallpeaper.png?raw=true",
        "precio": 49.99
    },
    {
        "id": 8,
        "titulo": "The Legend of Zelda: Breath of the Wild",
        "plataformas": ["Steam", "Epic Games", "Blizzard"],
        "genero": ["Acción", "Aventura"],
        "fecha": "03/03/2017",
        "desarrollador": "Nintendo",
        "editor": ["Nintendo"],
        "stock": 95,
        "caratula": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/caratula.png?raw=true",
        "captura": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/captura.png?raw=true",
        "wallpeaper": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/wallpeaper.png?raw=true",
        "precio": 54.99
    },
    {
        "id": 9,
        "titulo": "Among Us",
        "plataformas": ["Steam", "Epic Games", "Blizzard"],
        "genero": ["Multijugador", "Aventura", "Sandbox"],
        "fecha": "16/11/2018",
        "desarrollador": "Innersloth",
        "editor": ["Innersloth"],
        "stock": 75,
        "caratula": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/caratula.png?raw=true",
        "captura": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/captura.png?raw=true",
        "wallpeaper": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/wallpeaper.png?raw=true",
        "precio": 19.99
    },
    {
        "id": 10,
        "titulo": "Overwatch",
        "plataformas": ["Steam", "Epic Games", "Blizzard"],
        "genero": ["Shooter", "Multijugador"],
        "fecha": "24/05/2016",
        "desarrollador": "Blizzard Entertainment",
        "editor": ["Blizzard Entertainment"],
        "stock": 80,
        "caratula": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/caratula.png?raw=true",
        "captura": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/captura.png?raw=true",
        "wallpeaper": "https://github.com/zuoki/imagenesPF/blob/main/the%20witcher%203/wallpeaper.png?raw=true",
        "precio": 39.99
    },
];
