import { Inter } from 'next/font/google'
import './globals.css';
import NavBar from '@/components/navbar/navbar';

const inter = Inter({ subsets: ['latin'] })
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';

export const metadata = {
  title: 'Vorttex Gaming',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
			appearance={{
				baseTheme: dark,
			}}
		>
       <html lang="en">
       <link rel="icon" href="/favicon.ico" sizes="any" />
           <body className={inter.className}>
           <NavBar />
          {children}</body>
        </html>
    </ClerkProvider>
  )
}
