import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/navbar/navbar';

const inter = Inter({ subsets: ['latin'] });
import { ClerkProvider } from '@clerk/nextjs';

export const metadata = {
	title: 'Vorttex Gaming',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={inter.className}>
					<NavBar />
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
